# Scientific Computing with Python (Second Edition)

# Chapter 05

*We start by importing all from Numpy. As explained in Chapter 01 the examples are written assuming this import is initially done.*


In [1]:
from numpy import *

## 5.1 Array views and copies
### 5.1.1 Array views



In [2]:
M = array([[1.,2.],[3.,4.]])
v = M[0,:] # first row of M

In [3]:
v[-1] = 0.
v # array([[1.,0.]])

array([1., 0.])

In [4]:
M # array([[1.,0.],[3.,4.]]) # M is modified as well

array([[1., 0.],
       [3., 4.]])

In [5]:
v.base # array([[1.,0.],[3.,4.]])

array([[1., 0.],
       [3., 4.]])

In [6]:
print(M.base) # None

None


### 5.1.2 Slices as views

In [7]:
a = arange(4) # array([0.,1.,2.,3.])
b = a[[2,3]] # the index is a list [2,3]
b # array([2.,3.])

array([2, 3])

In [8]:
b.base is None # True, the data was copied

True

In [9]:
c = a[1:3] 
c.base is None # False, this is just a view

False

### 5.1.3 Generating views by transposing and reshaping

In [10]:
M = random.random_sample((3,3))
N = M.T
N.base is M # True

True

In [11]:
v = arange(10)
C = v.reshape(-1,1) # column matrix
C.base is v # True

True

### 5.1.4 Array copies

In [12]:
M = array([[1.,2.],[3.,4.]])
N = array(M.T) # copy of M.T

In [13]:
N.base is None # True

True

## 5.2 Comparing arrays

In [14]:
A = array([0.,0.])
B = array([0.,0.])
if abs(B-A) < 1e-10: # an exception is raised here
    print("The two arrays are close enough")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 5.2.1 Boolean arrays

In [ ]:
A = array([True,False]) # Boolean array
A.dtype # dtype('bool')

In [ ]:
M = array([[2, 3],
           [1, 4]])
M > 2 # array([[False, True],
             # [False, True]])

In [ ]:
M == 0 # array([[False, False],
             # [False, False]])

In [ ]:
N = array([[2, 3],
           [0, 0]])
M == N # array([[True, True],
       # [False, False]])

In [ ]:
A = array([[1,2],[3,4]])
B = array([[1,2],[3,3]])
A == B # creates array([[True, True], [True, False]]) 

In [ ]:
(A == B).all() # False

In [ ]:
(A != B).any() # True

In [ ]:
if (abs(B-A) < 1e-10).all():
    print("The two arrays are close enough")

### 5.2.2 Checking for array equality

In [ ]:
data = random.rand(2)*1e-3
small_error = random.rand(2)*1e-16
data == data + small_error # False
allclose(data, data + small_error, rtol=1.e-5, atol=1.e-8)   # True

In [ ]:
atol=1.e-5
rtol=1.e-8
(abs(A-B) < atol+rtol*abs(B)).all()

In [ ]:
data = 1e-3
error = 1e-16
data == data + error # False
allclose(data, data + error, rtol=1.e-5, atol=1.e-8)  #True

### 5.2.3 Boolean operations on arrays

In [ ]:
A = array([True, True, False, False])
B = array([True, False, True, False])
A and B # error!

In [ ]:
A & B # array([True, False, False, False])

In [ ]:
A | B # array([True, True, True, False])

In [ ]:
~A # array([False, False, True, True])

In [ ]:
data = linspace(1,100,100) # data 
deviation = random.normal(size=100) # the deviations
data = data + deviation 
# do not forget the parentheses in the next statement! 
exceptional = data[(deviation<-0.5)|(deviation>0.5)] 
exceptional = data[abs(deviation)>0.5] # same result 
small = data[(abs(deviation)<0.1)&(data<5.)] # small deviation and data

In [ ]:
exceptional, small

## 5.3 Array indexing
### 5.3.1 Indexing with Boolean arrays

In [ ]:
B = array([[True, False],
           [False, True]])
M = array([[2, 3],
           [1, 4]])
M[B] # array([2,4]), a vector

In [ ]:
M[B] = 0
M # [[0, 3], [1, 0]]

In [ ]:
M[B] = 10, 20
M # [[10, 3], [1, 20]]

In [ ]:
M[M>2] = 0    # all the elements > 2 are replaced by 0
M

### 5.3.2 Using the command where

In [ ]:
def H(x):
    return where(x < 0, 0, 1)
x = linspace(-1,1,11)  # [-1. -0.8 -0.6 -0.4 -0.2 0. 0.2 0.4 0.6 0.8 1. ]
print(H(x))            # [0 0 0 0 0 1 1 1 1 1 1]

In [ ]:
x = linspace(-4,4,5)
# [-4. -2.  0.  2.  4.]

print(where(x < 0, -x, x))
# [ 4., 2., 0, 2., 4.] ]
print(where(x > 0, 1, -1)) # [-1 -1 -1  1  1]

In [ ]:
a = arange(9)
b = a.reshape((3,3))

print(where(a > 5))   # (array([6, 7, 8]),)
print(where(b > 5))   # (array([2, 2, 2]), array([0, 1, 2]))

## 5.4 Performance and vectorization

In [ ]:
def my_prod(a,b):
    val = 0
    for aa, bb in zip(a,b):
        val += aa*bb
    return val

### 5.4.1 Vectorization

In [ ]:
v=arange(10)
w=zeros((10,))
for i in range(len(v)):
    w[i] = v[i] + 5
w

In [ ]:
w = v + 5
w

In [ ]:
def my_avg(A):
    m,n = A.shape
    B = A.copy()
    for i in range(1,m-1):
        for j in range(1,n-1):
            B[i,j] = (A[i-1,j] + A[i+1,j] + A[i,j-1] + A[i,j+1])/4
    return B

def slicing_avg(A):
    A[1:-1,1:-1] = (A[:-2,1:-1] + A[2:,1:-1] +
                    A[1:-1,:-2] + A[1:-1,2:])/4
    return A


In [ ]:
def my_func(x):
    y = x**3 - 2*x + 5
    if y>0.5:
        return y-0.5
    else:
        return 0

In [ ]:
[my_func(vk) for vk in v]

In [ ]:
vectorize(my_func)(v)

## 5.5 Broadcasting
### 5.5.1 Mathematical views


In [ ]:
vector = arange(4) # array([0.,1.,2.,3.])
vector + 1.        # array([1.,2.,3.,4.])

In [ ]:
C = arange(2).reshape(-1,1) # column
R = arange(2).reshape(1,-1) # row
C + R                       # valid addition: array([[0.,1.],[1.,2.]])

### 5.5.2 Broadcasting arrays

In [ ]:
M = array([[11, 12, 13, 14],
           [21, 22, 23, 24],
           [31, 32, 33, 34]])
v = array([100, 200, 300, 400])
M + v # works directly



In [ ]:
M + v.reshape(-1,1)

In [ ]:
M = array([[11, 12, 13, 14],
           [21, 22, 23, 24],
           [31, 32, 33, 34]])
v = array([100, 200, 300])
M+v

In [ ]:
M + v.reshape(-1,1)

### 5.5.3 Typical examples

In [ ]:
coeff=array([-1,-2,-3]).reshape(-1,1)
M*coeff

In [ ]:
coeff=array([-1,-2,-3,-4])
M*coeff

In [ ]:
u=array([1, 2])
v=array([1, 2, 3])
W=u.reshape(-1,1) + v
W

In [ ]:
x,y = ogrid[0:1:3j,0:1:3j] 
# x,y are vectors with the contents of linspace(0,1,3)
w = cos(x) + sin(2*y)
w

In [ ]:
x,y = ogrid[0:1:3j, 0:1:3j]
x, y

In [ ]:
x, y = ogrid.__getitem__((slice(0, 1, 3j),slice(0, 1, 3j)))
x, y 

## 5.6. Sparse matrices
### 5.6.1 Sparse matrix formats

In [ ]:
import scipy.sparse as sp
A = array([[1,0,2,0],[0,0,0,0],[3.,0.,0.,0.],[1.,0.,0.,4.]])
AS = sp.csr_matrix(A)

In [ ]:
AS.data

In [ ]:
AS.indptr

In [ ]:
AS.indices

In [ ]:
AS.nnz

In [ ]:
import scipy.sparse as sp
A = array([[1,0,2,0],[0,0,0,0],[3.,0.,0.,0.],[1.,0.,0.,4.]])
AS = sp.csc_matrix(A)
AS.data         # returns array([ 1., 3., 1., 2., 4.]) 

In [ ]:
AS.indptr       # returns array([0, 3, 3, 4, 5])

In [ ]:
AS.indices      # returns array([0, 2, 3, 0, 3])

In [ ]:
AS.nnz          # returns 5

In [15]:
import scipy.sparse as sp
A = array([[1,0,2,0],[0,0,0,0], [3.,0.,0.,0.], [1.,0.,0.,4.]]) 
AS = sp.lil_matrix(A)

In [16]:
AS.data     # returns array([[1.0, 2.0], [], [3.0], [1.0, 4.0]], dtype=object)

array([list([1.0, 2.0]), list([]), list([3.0]), list([1.0, 4.0])],
      dtype=object)

In [17]:
AS.rows     # returns array([[0, 2], [], [0], [0, 3]], dtype=object)

array([list([0, 2]), list([]), list([0]), list([0, 3])], dtype=object)

In [18]:
AS.nnz      # returns 5

5

In [19]:
BS = AS[1:3,0:2]
BS.data     # returns array([[], [3.0]], dtype=object)

array([list([]), list([3.0])], dtype=object)

In [20]:
BS.rows     # returns array([[], [0]], dtype=object)

array([list([]), list([0])], dtype=object)

In [21]:
AS[0,1] = 17 
AS.data # returns array([[1.0, 17.0, 2.0], [], [3.0], [1.0, 4.0]])

array([list([1.0, 17.0, 2.0]), list([]), list([3.0]), list([1.0, 4.0])],
      dtype=object)

In [22]:
AS.rows              # returns array([[0, 1, 2], [], [0], [0, 3]])

array([list([0, 1, 2]), list([]), list([0]), list([0, 3])], dtype=object)

In [23]:
AS.nnz               # returns 6

6

### 5.6.2 Generating sparse matrices

In [24]:
import scipy.sparse as sp
sp.eye(20,20,format = 'lil') 
sp.spdiags(ones((20,)),0,20,20, format = 'csr') 
sp.identity(20,format ='csc')

<20x20 sparse matrix of type '<class 'numpy.float64'>'
	with 20 stored elements in Compressed Sparse Column format>

In [25]:
import scipy.sparse as sp 
AS=sp.rand(20,200,density=0.1,format='csr')
AS.nnz # returns 400

400

In [26]:
import scipy.sparse as sp
Z=sp.csr_matrix((20,200))
Z.nnz    # returns 0

0

### 5.6.3 Sparse matrix methods

In [27]:
AS.toarray # converts sparse formats to a numpy array 
AS.tocsr
AS.tocsc
AS.tolil

<bound method csr_matrix.tolil of <20x200 sparse matrix of type '<class 'numpy.float64'>'
	with 400 stored elements in Compressed Sparse Row format>>

In [28]:
import scipy.sparse as sp
def sparse_sin(A):
    if not (sp.isspmatrix_csr(A) or sp.isspmatrix_csc(A)):
        A = A.tocsr()
    A.data = sin(A.data)
    return A

In [29]:
import scipy.sparse as sp
A = array([[1,0,2,0],[0,0,0,0],[3.,0.,0.,0.],[1.,0.,0.,4.]])
AS = sp.csr_matrix(A)
b = array([1,2,3,4])
c = AS.dot(b)      # returns array([ 7., 0., 3., 17.])
c

array([ 7.,  0.,  3., 17.])

In [30]:
C = AS.dot(AS)     # returns  csr_matrix
d = dot(AS,b)      # does not return the expected result!
d

array([<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>,
       <4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>,
       <4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>,
       <4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>], dtype=object)